remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: douira
description: My personal website\nHe/Him ğŸ³ï¸â€ğŸŒˆ

logo: /assets/img/profile picture.jpg
show_downloads: false
